package android.databinding.ksp

import android.databinding.annotationprocessor.BindableBag
import android.databinding.annotationprocessor.ProcessBindable
import android.databinding.tool.CompilerArguments
import android.databinding.tool.LibTypes
import android.databinding.tool.reflection.ModelAnalyzer
import android.databinding.tool.util.GenerationalClassUtil
import android.databinding.tool.util.L
import android.databinding.tool.util.LoggedErrorException
import android.databinding.tool.writer.BRWriter
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration

//import javax.lang.model.element.Element
//import javax.lang.model.element.ElementKind
//import javax.lang.model.element.ExecutableElement
//import javax.lang.model.element.VariableElement

class ProcessBindable : ProcessBindable() {
    private lateinit var mProperties: Intermediate
    private val mLayoutVariables = HashMap<String, HashSet<String>>()

    private var mResolver : Resolver? = null

    //TODO ksp
    override fun onHandleKspStep(
        resolver: Resolver,
        processingEnvironment: SymbolProcessorEnvironment?,
        args: CompilerArguments
    ): Boolean {

        mResolver = resolver

        if (mProperties == null) {
            mProperties = ProcessBindable.IntermediateV1(args.modulePackage)
            mergeLayoutVariables()
            mLayoutVariables.clear()

            val libTypes = ModelAnalyzer.getInstance().libTypes
            val observableType = resolver.getClassDeclarationByName(resolver.getKSNameFromString(libTypes.observable))

            AnnotationUtil.getElementsAnnotatedWith(resolver, libTypes.bindableClass.name)
                .forEach { element ->
                    val parentElement = element.parentDeclaration as? KSClassDeclaration

                    if (parentElement?.classKind == ClassKind.CLASS &&
                        isGeneratedViewBinding(resolver, libTypes, parentElement)) {
                        // Skip generated view bindings
                        return@forEach
                    }

                    try {
                        val enclosingElement = element.parentDeclaration as? KSClassDeclaration
                        val kind = enclosingElement?.classKind
                        if (kind != ClassKind.CLASS && kind != ClassKind.INTERFACE) {
                            L.e("Bindable must be on a member field or method. The enclosing type is %s",
                                    kind)
                        }

                        val enclosing = enclosingElement?.asStarProjectedType()
                        enclosing?.let {
                            if (observableType?.asStarProjectedType()?.isAssignableFrom(it) != true) {
                                L.e("Bindable must be on a member in an Observable class. %s is not Observable",
                                    enclosingElement?.simpleName)
                            }
                        }


                        val name = getPropertyName(element)
                        name?.let {
                            checkNotNull(mProperties) {
                                "Must receive app/library info before Bindable fields."
                            }

                            mProperties.addProperty(enclosingElement?.qualifiedName?.asString(), it)
                        }
                    } catch (e: LoggedErrorException) {
                        // We'll get them later when we do the messages
                    }
                }

            GenerationalClassUtil.get().write(
                mProperties.getPackage(),
                GenerationalClassUtil.ExtensionFilter.BR,
                mProperties
            )
            generateBRClasses(resolver, args, mProperties.getPackage())
        }

        return true
    }

    private fun isGeneratedViewBinding(
        resolver: Resolver,
        libTypes: LibTypes,
        element: KSClassDeclaration
    ): Boolean {
        // Note: Ideally, we'd search for the @Generated({ "Android Data Binding "}) annotation to
        // know whether the target class was generated by us or not. However, that annotation was
        // not introduced until Java 8, so the classes we really want to know about
        // (".../generated/.../XyzBinding.java") are not annotated. As a secondary signal, we check
        // if the class inherits from ViewDataBinding, which user-code is not expected to do.
        //TODO ksp to test
        val viewDataBinding = resolver.getClassDeclarationByName(resolver.getKSNameFromString(libTypes.viewDataBinding))?.asStarProjectedType()
        return viewDataBinding?.isAssignableFrom(element.asStarProjectedType()) == true
    }

    private fun getPropertyName(element: KSDeclaration): String? {
        return when (element) {
            is KSPropertyDeclaration -> stripPrefixFromField(element)
            is KSFunctionDeclaration -> stripPrefixFromMethod(element)
            else -> {
                L.e("@Bindable is not allowed on %s", element)
                null
            }
        }
    }

    private fun stripPrefixFromField(element: KSPropertyDeclaration): String {
        val name = element.simpleName.asString()
        if (name.length >= 2) {
            val firstChar = name[0]
            val secondChar = name[1]
            if (name.length > 2 && firstChar == 'm' && secondChar == '_') {
                val thirdChar = name[2]
                if (thirdChar.isJavaIdentifierStart()) {
                    return "${thirdChar.lowercaseChar()}${name.subSequence(3, name.length)}"
                }
            } else if ((firstChar == 'm' && secondChar.isUpperCase()) ||
                (firstChar == '_' && secondChar.isJavaIdentifierStart())) {
                return "${secondChar.lowercaseChar()}${name.subSequence(2, name.length)}"
            }
        }
        return name.toString()
    }

    private fun stripPrefixFromMethod(element: KSFunctionDeclaration): String? {
        val name = element.simpleName.asString()
        val propertyName = when {
            isGetter(element) || isSetter(element) -> name.subSequence(3, name.length)
            isBooleanGetter(element) -> name.subSequence(2, name.length)
            else -> {
                L.e("@Bindable associated with method must follow JavaBeans convention %s", element)
                return null
            }
        }
        val firstChar = propertyName[0]
        return "${firstChar.lowercaseChar()}${propertyName.subSequence(1, propertyName.length)}"
    }

    private fun isGetter(element: KSFunctionDeclaration): Boolean {
        val name = element.simpleName.asString()
        return prefixes(name,"get") &&
                name[3].isJavaIdentifierStart() &&
                element.parameters.isEmpty() &&
                element.returnType.kind != TypeKind.VOID
    }

    private fun isSetter(element: KSFunctionDeclaration): Boolean {
        val name = element.simpleName.asString()
        return prefixes(name,"set") &&
                name[3].isJavaIdentifierStart() &&
                element.parameters.size == 1 &&
                element.returnType.kind == TypeKind.VOID
    }

    private fun isBooleanGetter(element: KSFunctionDeclaration): Boolean {
        val name = element.simpleName.asString()
        return prefixes(name,"is") &&
                name[2].isJavaIdentifierStart() &&
                element.parameters.isEmpty() &&
                element.returnType.kind == TypeKind.BOOLEAN
    }

    private fun generateBRClasses(
        processingEnv: Resolver,
        compilerArgs: CompilerArguments,
        pkg: String
    ) {
        try {
            val artifactType = compilerArgs.artifactType
            L.d("************* Generating BR file %s. use final: %s", pkg, artifactType.name)

            val properties = HashSet<String>().apply {
                mProperties.captureProperties(this)
            }

            // TODO ksp BindableBag
            val bindableBag = BindableBag(
                compilerArgs,
                getProperties(mProperties),
                kspResolver = processingEnv
            )

            val writer = writer
            val useFinal = compilerArgs.isApp || compilerArgs.isFeature || compilerArgs.isTestVariant
            val brWriter = BRWriter(useFinal)

            bindableBag.toBeGenerated.forEach { brWithValues ->
                val output = brWriter.write(brWithValues)
                writer.writeToFile("${brWithValues.pkg}.BR", output)
            }

            mCallback.onBrWriterReady(
                bindableBag.variableIdLookup,
                bindableBag.writtenPackages
            )
        } catch (e: LoggedErrorException) {
            // This will be logged later
        }
    }
}